config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  get 'home', to: 'groups#index', as: 'home'
  root to: 'splash#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }, path_names: {
    new_password: 'forgot',
    edit_password: 'reset'
  }
  resources :groups, only: [:index, :show, :new, :create]
  resources :entities, only: [:create, :new]
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user

    # Define rules for entities
    can :create, Entity
    can %i[update read destroy], Entity, author_id: user.id

    # Define rules for groups
    can :create, Group
    can %i[update read destroy], Group, creator_id: user.id

    # Additional rules for other actions like :update and :destroy if needed
    # For example, allow users to update and destroy their own entities
    can :update, Entity, author_id: user.id
    can :destroy, Entity, author_id: user.id

    # Add any other rules based on your application's requirements

    if user.admin?
      can :manage, :all # Admins can manage all resources
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_and_belongs_to_many :entities

  validates :name, presence: true
  validates :icon, presence: false
  validates :creator_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, foreign_key: 'creator_id', dependent: :destroy

  has_many :entities, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true

  def admin?
    self.admin == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_current_user
  before_action :store_previous_page, only: [:new]

  def set_current_user
    @user = current_user if user_signed_in?
  end

  def store_previous_page
    session[:previous_page] = request.referer
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def new
    @entity = Entity.new
    @header_text = 'CREATE TRANSACTION'
    @button_text = 'Save'
  end

  def create
    @entity = Entity.new(entity_params)
    @entity.author_id = current_user.id

    if @entity.save
      @entity.groups.reload
      redirect_to group_path(@entity.groups.first), notice: 'Entity was successfully created.'
    else
      render :new
    end
  end

  private

  def set_entity
    @entity = Entity.find(params[:id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @header_text = 'CATEGORIES'
    if current_user.admin?
      @groups = Group.all # Admins can see all groups
    else
      @groups = current_user ? current_user.groups : Group.none
    end
  end

  def show
    @group = Group.includes(entities: :user).find(params[:id])
    @header_text = @group.name.upcase
    @entities = @group.entities.order(created_at: :desc)
  end

  def new
    @header_text = 'CREATE CATEGORY'
    @button_text = 'Save'
  end

  def create
    @group = Group.new(group_params)
    @group.creator_id = current_user.id

    if @group.save
      redirect_to home_path, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @header_text = 'TRANSACTIONS'
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @is_splash_index = true
    if user_signed_in? # Check if the user is logged in
      redirect_to home_path # Redirect logged-in users to the root path (or any other path)
    else
      # Controller logic for unauthenticated users
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  def new
    @header_text = 'FORGOT'
    @button_text = 'Next'
    super
  end

  def edit
    @header_text = 'REDEFINE'
    @button_text = 'Next'
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  def new
    @header_text = 'REGISTER'
    @button_text = 'NEXT'
    super
  end

  def edit
    @header_text = 'EDIT'
    @button_text = 'Save'
    super
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    @header_text = 'LOGIN'
    @button_text = 'Log In'
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/entities/new.html.erb
<div class="h-screen flex flex-col items-center justify-start max-w-screen-sm mx-auto bg-gray-200">
  <%= form_with(model: @entity, url: entities_path, method: :post, html: { class: 'w-full mb-4' }) do |form| %>
    <%= form.text_field :name, class: 'w-full bg-white border-b border-gray-300 py-2 px-2 focus:outline-none focus:border-gray-500', autofocus: true, placeholder: 'Transaction Name' %>
    <%= form.number_field :amount, class: 'w-full bg-white border-b border-gray-300 py-2 px-2 focus:outline-none focus:border-gray-500', autofocus: true, placeholder: 'Amount' %>
    <%= form.collection_check_boxes(:group_ids, current_user.groups, :id, :name) %>
    <% if @entity.errors.any? %>
      <div class="alert alert-danger">
        <h2>Errors:</h2>
        <ul>
          <% @entity.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

<% end %>
</div>

app/views/groups/index.html.erb
<div class="h-screen flex flex-col items-center justify-start max-w-screen-sm mx-auto bg-gray-200">
  <% if @groups.any? %>
    <div class="min-h-content w-full p-2">
      <% @groups.includes(:entities).each do |group| %>
        <div class="p-2 flex bg-white items-center mb-2">
          <div class="h-[80px] w-[80px] bg-cover" style="background-image: url('<%= group.icon %>')"></div>
          <div class="pl-2 h-20 flex flex-col w-[90%] justify-center">
            <div class="flex h-full w-full justify-between">
              <div class="flex h-full items-center">
                <span class="text-gray-500"><%= link_to group.name, group %></span>
              </div>
              <div class="flex h-full items-center">
                <span class="text-black font-bold">
                  <% sum_amount = group.entities.sum(:amount) %>
                  <%= number_to_currency(sum_amount, unit: '$', precision: 2) %>
                </span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>There are no categories.</p>
  <% end %>
</div>
<div class="fixed bottom-0 right-0 p-4 w-full">
  <div class="max-w-screen-sm mx-auto pb-20 px-20 flex justify-end">
    <a href="<%= new_group_path %>">
      <i id="new-group" class="fixed bi bi-plus-circle-fill z-90 rounded-full drop-shadow-lg flex justify-center items-center bg-white text-green-400 text-6xl hover:drop-shadow-2xl"></i>
    </a>
  </div>
</div>

app/views/groups/new.html.erb
<div class="h-screen flex flex-col items-center justify-start max-w-screen-sm mx-auto bg-gray-200">
  <%= form_with(model: @group, url: groups_path, html: { class: 'w-full mb-4' }) do |form| %>
      <%= form.text_field :name, class: 'w-full bg-white border-b border-gray-300 py-2 px-2 focus:outline-none focus:border-gray-500', autofocus: true, placeholder: 'Group Name' %>
      <%= form.text_field :icon, class: 'w-full bg-white border-b border-gray-300 py-2 px-2 focus:outline-none focus:border-gray-500', autofocus: true, placeholder: 'Icon Link' %>
  <% end %>
</div>

app/views/groups/show.html.erb
<div class="h-screen flex flex-col items-center justify-start max-w-screen-sm mx-auto bg-gray-200">

  <div class="w-full grid bg-blue-500 grid-cols-3 gap-0">
    <div class="text-center order-1 p-2"></div>
    <div id="recent" class="text-center p-2 text-white order-2 text-opacity-100">Most recent</div>
    <div class="text-center order-3 p-2"></div>
  </div>

  <!-- New div with flex layout -->
  <div class="w-full bg-white py-6 px-2 flex justify-between">
    <span class="text-gray-500">Total Amount</span>
    <span class="font-bold"><% sum_amount = @group.entities.sum(:amount) %>
      <%= number_to_currency(sum_amount, unit: '$', precision: 2) %></span>
  </div>

  <% if @group.entities.any? %>
    <div id="entityContainer" class="min-h-content w-full p-2">
      <% @group.entities.sort_by(&:created_at).reverse.each do |entity| %>
        <% tailwind_colors = %w[red orange yellow green teal blue indigo purple pink] %>
        <div id="entity_<%= entity.id %>" class="entity-item p-2 flex bg-white items-center mb-2">
          <div class="h-[80px] w-[80px] bg-<%= tailwind_colors.sample %>-500"></div>
          <div class="pl-2 h-20 flex flex-col w-[90%] justify-center">
            <div class="flex h-full w-full justify-between">
              <div class="flex h-full items-end">
                <span class="text-gray-500"><%= entity.name %></span>
              </div>
              <div class="flex h-full items-end">
                <span class="text-black font-bold">$<%= entity.amount %></span>
              </div>
            </div>
            <div class="pt-4">
              <span id="entity_<%= entity.id %>_date" class="text-gray-500 text-sm"><%= entity.created_at.to_s %></span>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>No transactions created for this group.</p>
  <% end %>


</div>
<div class="fixed bottom-0 right-0 p-4 w-full">
  <div class="max-w-screen-sm mx-auto pb-20 px-20 flex justify-end">
    <a href="<%= new_entity_path %>">
      <i id="new-entity" class="fixed bi bi-plus-circle-fill z-90 rounded-full drop-shadow-lg flex justify-center items-center bg-white text-green-400 text-6xl hover:drop-shadow-2xl"></i>
    </a>
  </div>
</div>

app/views/home/index.html.erb
<div class="h-screen flex flex-col items-center justify-start max-w-screen-sm mx-auto bg-gray-200">

  <div class="w-full grid bg-blue-500 grid-cols-3 gap-0">
    <div id="empty" class="text-center order-1 p-2">
      <!-- Empty content -->
    </div>
    <div id="recent" class="text-center p-2 text-white order-2 text-opacity-100 hover:bg-blue-400"><a href="#">Most recent</a></div>
    <div id="ancient" class="text-center p-2 text-white order-3 text-opacity-75 hover:bg-blue-400"><a href="#">Most ancient</a></div>
  </div>

  <!-- New div with flex layout -->
  <div class="w-full bg-white py-6 px-2 flex justify-between">
    <span class="text-gray-500">Gift credit</span>
    <span class="font-bold">$45.00</span>
  </div>

  <div class="min-h-content w-full p-2">
    <div class="p-2 flex bg-white items-center">
      <div class="h-[80px] w-[80px] bg-yellow-500"></div>
      <div class="pl-2 h-20 flex flex-col w-[90%] justify-center">
        <div class="flex h-full w-full justify-between">
          <div class="flex h-full items-end">
            <span class="text-gray-500">MC Donnalds</span>
          </div>
          <div class="flex h-full items-end">
            <span class="text-black font-bold">$17.00</span>
          </div>
        </div>
        <div class="pt-4">
          <span class="text-gray-500 text-sm">12 Apr 2023</span>
        </div>
      </div>
    </div>
  </div>

</div>
<div class="fixed bottom-0 right-0 p-4 w-full">
  <div class="max-w-screen-sm mx-auto pb-20 px-20 flex justify-end">
    <button onclick="buttonHandler()" title="Contact Sale">
      <i class="fixed bi bi-plus-circle-fill z-90 rounded-full drop-shadow-lg flex justify-center items-center bg-white text-green-400 text-6xl hover:drop-shadow-2xl"></i>
    </button>
  </div>
</div>
<script>
    // Declare variables in the outer scope
    let empty = document.getElementById('empty');
    let recent = document.getElementById('recent');
    let ancient = document.getElementById('ancient');

    if (recent) {
        recent.addEventListener('click', function () {
            if (recent.classList.contains('order-1')) {
                recent.classList.remove('order-1');
                recent.classList.add('order-2');
                ancient.classList.remove('text-opacity-100');
                ancient.classList.add('text-opacity-75');
                recent.classList.remove('text-opacity-75');
                recent.classList.add('text-opacity-100');
                empty.classList.remove('order-3');
                empty.classList.add('order-1');
                ancient.classList.remove('order-2');
                ancient.classList.add('order-3');
            }
        });
    }

    if (ancient) {
        ancient.addEventListener('click', function () {
            if (recent.classList.contains('order-2')) {
                recent.classList.remove('order-2');
                recent.classList.add('order-1');
                recent.classList.remove('text-opacity-100');
                recent.classList.add('text-opacity-75');
                ancient.classList.remove('text-opacity-75');
                ancient.classList.add('text-opacity-100');
                empty.classList.remove('order-1');
                empty.classList.add('order-3');
                ancient.classList.remove('order-3');
                ancient.classList.add('order-2');
                ancient.style.opacity = '1';
            }
        });
    }

</script>

app/views/splash/index.html.erb
<div class="h-screen flex flex-col items-center justify-center max-w-screen-sm mx-auto p-2">
  <h1 class="text-7xl font-bold text-center my-[50%]" style="font-family: 'Dancing Script', cursive;">4Economy</h1>
  <a href="<%= new_user_session_path %>" class="bg-blue-500 flex items-center justify-center text-white w-full p-2 h-16 text-center rounded-lg text-xl mb-4">LOG IN</a>
  <a href="<%= new_user_registration_path %>" class="border flex items-center justify-center border-none text-gray-700 h-16 w-full p-2 text-center rounded-lg text-xl">SIGN UP</a>
</div>