config/routes.rb
Rails.application.routes.draw do
  get 'splash/index'
  get 'home', to: 'groups#index', as: 'home'
  root to: 'splash#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }, path_names: {
    new_password: 'forgot',
    edit_password: 'reset'
  }
  resources :groups, only: [:index, :show, :new, :create]
  resources :entities, only: [:create, :new]
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user

    # Define rules for entities
    can :create, Entity
    can %i[update read destroy], Entity, author_id: user.id

    # Define rules for groups
    can :create, Group
    can %i[update read destroy], Group, creator_id: user.id

    # Additional rules for other actions like :update and :destroy if needed
    # For example, allow users to update and destroy their own entities
    can :update, Entity, author_id: user.id
    can :destroy, Entity, author_id: user.id

    # Add any other rules based on your application's requirements

    if user.admin?
      can :manage, :all # Admins can manage all resources
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  has_and_belongs_to_many :groups

  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_and_belongs_to_many :entities

  validates :name, presence: true
  validates :icon, presence: false
  validates :creator_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, foreign_key: 'creator_id', dependent: :destroy

  has_many :entities, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true

  def admin?
    self.admin == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_current_user
  before_action :store_previous_page, only: [:new]

  def set_current_user
    @user = current_user if user_signed_in?
  end

  def store_previous_page
    session[:previous_page] = request.referer
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def new
    @entity = Entity.new
    @header_text = 'CREATE TRANSACTION'
    @button_text = 'Save'
  end

  def create
    @entity = Entity.new(entity_params)
    @entity.author_id = current_user.id

    if @entity.save
      @entity.groups.reload
      redirect_to group_path(@entity.groups.first), notice: 'Entity was successfully created.'
    else
      render :new
    end
  end

  private

  def set_entity
    @entity = Entity.find(params[:id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @header_text = 'CATEGORIES'
    if current_user.admin?
      @groups = Group.all # Admins can see all groups
    else
      @groups = current_user ? current_user.groups : Group.none
    end
  end

  def show
    @group = Group.includes(entities: :user).find(params[:id])
    @header_text = @group.name.upcase
    @entities = @group.entities.order(created_at: :desc)
  end

  def new
    @header_text = 'CREATE CATEGORY'
    @button_text = 'Save'
  end

  def create
    @group = Group.new(group_params)
    @group.creator_id = current_user.id

    if @group.save
      redirect_to home_path, notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @header_text = 'TRANSACTIONS'
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @is_splash_index = true
    if user_signed_in? # Check if the user is logged in
      redirect_to home_path # Redirect logged-in users to the root path (or any other path)
    else
      # Controller logic for unauthenticated users
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  def new
    @header_text = 'FORGOT'
    @button_text = 'Next'
    super
  end

  def edit
    @header_text = 'REDEFINE'
    @button_text = 'Next'
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new
    @header_text = 'LOGIN'
    @button_text = 'Log In'
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/layouts/_navs.html.erb
<nav class="bg-blue-500 p-4 flex items-center justify-between h-12 flex-row max-w-screen-sm mx-auto p-2">
  <!-- Left Arrow Icon -->
  <% if !user_signed_in? || (user_signed_in? && request.path != home_path) %>
    <!-- Back button for logged-in users -->
    <div class="text-white text-2xl">
      <a href="<%= splash_index_path %>" class="text-white text-2xl">
        <i class="fas fa-arrow-left"></i>
      </a>
    </div>
    <h1 class="text-white pnbold text-xl"><%= @header_text %></h1>

    <button type="submit" class="text-white text-align-right" id="submitFormButton">
      <%= @button_text %>
    </button>
    </nav>
  <% else %>
    <nav class="relative py-4 flex justify-between items-center">
      <div class="">
        <button class="navbar-burger flex items-center text-white">
          <svg class="block h-6 w-6 fill-current" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <title>Mobile menu</title>
            <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"></path>
          </svg>
        </button>
      </div>
    </nav>
    <h1 class="text-white pnbold text-xl"><%= @header_text %></h1>

    <button type="submit" class="text-white text-align-right" id="submitFormButton">
      <%= @button_text %>
    </button>
    </nav>
<div class="navbar-menu flex-row max-w-screen-sm mx-auto hidden">
  <nav class="flex flex-col h-screen h-screen-sm w-screen-sm max-w-screen-sm py-6 pl-6 bg-blue-500 border-r">
    <div class="flex items-center mb-8 mr-6">
      <a class="mr-auto text-3xl font-bold leading-none" href="#">
      </a>
      <button class="navbar-close">
        <svg class="h-6 w-6 text-white cursor-pointer hover:text-gray-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
        </svg>
      </button>
    </div>
    <div>
      <div class="flex flex-col items-center">
        <div class="rounded-full overflow-hidden w-24 h-24">
          <img src="https://avatars.githubusercontent.com/u/15636209?v=4" alt="User Avatar">
        </div>
        <p class="my-4 text-center text-white text-2xl"><%= @user.name %></p>
      </div>
      <ul>
        <li class="mb-1 flex items-center">
          <div class="rounded-full w-10 h-10 pt-0.5 flex flex-col items-center justify-between border border-white">
            <i class="bi bi-gear text-white text-2xl"></i>
          </div>
          <div class="border-b ml-4 border-white w-[85%]">
            <a class="block p-4 pl-0 text-xl text-white hover:bg-blue-50 hover:text-blue-600 rounded" href="<%= home_path %>">Categories</a>
          </div>
        </li>
        <li class="mb-1 flex items-center">
          <div class="rounded-full w-10 h-10 pt-0.5 flex flex-col items-center justify-between border border-white">
            <i class="bi bi-geo-alt text-white text-2xl"></i>
          </div>
          <div class="border-b ml-4 border-white w-[85%]">
            <a class="block p-4 pl-0 text-xl text-white hover:bg-blue-50 hover:text-blue-600 rounded" href="<%= new_group_path %>">New Categories</a>
          </div>
        </li>
        <li class="mb-1 flex items-center">
          <div class="rounded-full w-10 h-10 flex flex-col items-center justify-between border border-white">
            <i class="bi bi-box-arrow-up text-2xl text-white"></i>
          </div>
          <div class="border-b ml-4 border-white w-[85%]">
            <a class="block p-4 pl-0 text-xl text-white hover:bg-blue-50 hover:text-blue-600 rounded" href="<%= new_entity_path %>">New Transactions</a>
          </div>
        </li>
        <li class="mb-1 flex items-center">
          <div class="rounded-full w-10 h-10 flex flex-col items-center justify-between border border-white">
            <i class="bi bi-box-arrow-right ml-1 mt-0.5 text-2xl text-white"></i>
          </div>
          <div class="ml-4 w-[85%] hover:bg-blue-50 hover:text-blue-600 rounded">
            <%= button_to(destroy_user_session_path, class: 'block p-4 pl-0 text-xl text-white hover:bg-blue-50 hover:text-blue-600 rounded', method: :delete) do %>
              Log Out
            <% end %>
          </div>
        </li>
      </ul>

    </div>
  </nav>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FourEconomy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400&display=swap">
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="https://github.com/redmarverick/blog_app/blob/DEV/fonts/Proxima-Nova-Light.otf">
    <link rel="stylesheet" type="text/css" href="https://github.com/redmarverick/blog_app/blob/DEV/fonts/Proxima-Nova-Bold.otf">
    <style>.pnlight {font-family: 'Proxima Nova Light', sans-serif;} .pnbold {font-family: 'Proxima Nova Bold', sans-serif;}</style>
  </head>
    <%= javascript_importmap_tags %>
  </head>

  <body class="pnlight">
  <% unless @is_splash_index %>
    <%= render partial: 'layouts/navs' %>
  <% end %>
    <%= yield %>
  <script async>
      document.addEventListener('DOMContentLoaded', function() {
          const submitFormButton = document.getElementById('submitFormButton');
          if (submitFormButton) {
              submitFormButton.addEventListener('click', function() {
                  const form = document.querySelector('form');
                  form.submit();
              });
          } else {
              console.error('Button element not found');
          }
      });

      document.addEventListener('DOMContentLoaded', function() {
          const body = document.body; // Get a reference to the body element

          // open
          const burger = document.querySelectorAll('.navbar-burger');
          const menu = document.querySelectorAll('.navbar-menu');

          if (burger.length && menu.length) {
              for (var i = 0; i < burger.length; i++) {
                  burger[i].addEventListener('click', function() {
                      for (var j = 0; j < menu.length; j++) {
                          menu[j].classList.toggle('hidden');
                      }
                      body.classList.toggle('overflow-hidden'); // Toggle overflow-hidden class on body
                  });
              }
          }

          // close
          const close = document.querySelectorAll('.navbar-close');
          const backdrop = document.querySelectorAll('.navbar-backdrop');

          if (close.length) {
              for (var i = 0; i < close.length; i++) {
                  close[i].addEventListener('click', function() {
                      for (var j = 0; j < menu.length; j++) {
                          menu[j].classList.toggle('hidden');
                      }
                      body.classList.toggle('overflow-hidden'); // Toggle overflow-hidden class on body
                  });
              }
          }

          if (backdrop.length) {
              for (var i = 0; i < backdrop.length; i++) {
                  backdrop[i].addEventListener('click', function() {
                      for (var j = 0; j < menu.length; j++) {
                          menu[j].classList.toggle('hidden');
                      }
                      body.classList.toggle('overflow-hidden'); // Toggle overflow-hidden class on body
                  });
              }
          }
      });


  </script>
  </body>
</html>